/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import chat.server.Server;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;

/**
 *
 * @author Joco
 */
public class ChatWindow extends javax.swing.JFrame {

    private chat.Chat chatUser;

    private String userName;
    private String ipAddress;

    /**
     * Creates new form ChatWindow
     */
    public ChatWindow() {

        initComponents();
        createChat();
        JRootPane rootPane = getRootPane();
        rootPane.setDefaultButton(btnSend);
        tFSend.requestFocus();
        setLocationRelativeTo(null);
    }

    private void createChat() {

        InitDialog dialog = new InitDialog(this);
        dialog.setVisible(true);

        userName = dialog.getName();
        ipAddress = dialog.getIpAddress();
        while (true) {
            try {

                if (dialog.isServer()) {
                    chatUser = new chat.server.Server(userName, tAChat, jListUsers);
                    chatUser.start();
                    setTitle("Szerver - " + userName);
                    break;
                } else {
                    chatUser = new chat.client.Client(ipAddress, userName, tAChat, jListUsers);
                    chatUser.start();
                    setTitle("Kliens - " + userName);
                    break;
                }
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this,
                        "Hiba történt a " + (dialog.isServer() ? "szerver" : "kliens") + " létrehozása közben!\n\"" + ex.getMessage() + "\"",
                        "Váratlan hiba történt",
                        JOptionPane.ERROR_MESSAGE);
                dialog.setVisible(true);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tAChat = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        tFSend = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListUsers = new javax.swing.JList<>();

        jButton1.setText("jButton1");

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 400));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setPreferredSize(new java.awt.Dimension(400, 300));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(350, 400));

        tAChat.setColumns(20);
        tAChat.setRows(5);
        tAChat.setFocusable(false);
        jScrollPane1.setViewportView(tAChat);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));
        jPanel1.add(tFSend);

        btnSend.setText("Küldés");
        btnSend.setFocusable(false);
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        jPanel1.add(btnSend);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jListUsers.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListUsers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListUsers.setFocusable(false);
        jListUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListUsersMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jListUsers);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        try {

            if (tFSend.getText().length() > 0) {
                String text = userName + ":" + tFSend.getText();
                if (chatUser instanceof Server) {
                    ((Server) chatUser).setSentBy(0);
                }
                chatUser.sendMessage(text);
                tFSend.setText("");
                tFSend.requestFocus();
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,
                    "Üzenetküldés hiba!",
                    "Hiba történt az üzenet küldése közben\n"
                    + ex.getMessage(),
                    JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnSendActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            System.out.println("Closing sockets");
            chatUser.closeSocket();
            chatUser.join();
        } catch (InterruptedException ex) {
            System.out.println("InterruptedMain" + ex);
        }

    }//GEN-LAST:event_formWindowClosing

    private void jListUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListUsersMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jListUsersMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSend;
    private javax.swing.JButton jButton1;
    private javax.swing.JList<String> jListUsers;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextArea tAChat;
    private javax.swing.JTextField tFSend;
    // End of variables declaration//GEN-END:variables
}
