/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JOptionPane;

/**
 *
 * @author Joco
 */
public class InitDialog extends javax.swing.JDialog {

    private String name;
    private boolean server;
    private String ipAddress;

    /**
     * Creates new form InitDialog
     */
    public InitDialog(java.awt.Frame parent) {
        super(parent, true);
        name = null;
        ipAddress = null;
        initComponents();
        setLocationRelativeTo(null);
        jTFIPAddress.requestFocus();
        jTFIPAddress.selectAll();
        this.getRootPane().setDefaultButton(btnOk);
        setTitle("Chat");
    }

    public boolean isServer() {
        return server;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRBtnClient = new javax.swing.JRadioButton();
        jRBtnServer = new javax.swing.JRadioButton();
        jTFIPAddress = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTFUserName = new javax.swing.JTextField();
        btnOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        buttonGroup1.add(jRBtnClient);
        jRBtnClient.setSelected(true);
        jRBtnClient.setText("Kliens");
        jRBtnClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBtnClientActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBtnServer);
        jRBtnServer.setText("Szerver");
        jRBtnServer.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jRBtnServer.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jRBtnServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBtnServerActionPerformed(evt);
            }
        });

        jTFIPAddress.setText("localhost");

        jLabel1.setText("Felhasználónév:");

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRBtnServer)
                        .addGap(18, 18, 18)
                        .addComponent(jRBtnClient)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFIPAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnOk)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBtnServer)
                    .addComponent(jRBtnClient)
                    .addComponent(jTFIPAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOk))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRBtnServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBtnServerActionPerformed
        if (jRBtnServer.isSelected()) {
            server = true;
            jTFUserName.requestFocus();
            jTFIPAddress.setVisible(false);
        }
    }//GEN-LAST:event_jRBtnServerActionPerformed

    private void jRBtnClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBtnClientActionPerformed
        if (jRBtnClient.isSelected()) {
            server = false;
            jTFIPAddress.setVisible(true);
//            if (jTFUserName.getText().length() > 0) {
            jTFIPAddress.requestFocus();
            jTFIPAddress.selectAll();
//            } 

        }

    }//GEN-LAST:event_jRBtnClientActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        name = jTFUserName.getText();
        if (name.matches("[\\w]+")) {

            if (jRBtnClient.isSelected()) {

                if (jTFIPAddress.getText().matches("^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$")
                        || jTFIPAddress.getText().equals("localhost")) {
                    ipAddress = jTFIPAddress.getText();
                    setVisible(false);

                } else {
                    JOptionPane.showMessageDialog(this, "Nem jó az IP cím!", "Input error!", JOptionPane.ERROR_MESSAGE);
                }
            }else setVisible(false);

        } else {
            JOptionPane.showMessageDialog(this, "Nem jó a név!", "Input error!", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnOkActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    public String getName() {
        return name;
    }

    public String getIpAddress() {
        return ipAddress;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRBtnClient;
    private javax.swing.JRadioButton jRBtnServer;
    private javax.swing.JTextField jTFIPAddress;
    private javax.swing.JTextField jTFUserName;
    // End of variables declaration//GEN-END:variables
}
